---
title: "Lecture 1: Financial Market Integration in the Early Modern Period" 
author: | 
    | Dr. Gabriel Geisler Mesevage 
    | gabriel.mesevage@kcl.ac.uk
    | Office Hours: Tues. 11am & Weds. 11am
date: "Last update: `r format(Sys.time(), '%d %B, %Y')`"
output: 
  xaringan::moon_reader:
    nature:
      beforeInit: "helper_functions/macros.js"
      ratio: '16:9'
    lib_dir: libs
    css: ["xaringan-themer.css", "helper_functions/extra.css"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE,
                      message = FALSE, fig.align='center', fig.retina=3,
                      out.width="75%")

source("helper_functions/helper_print_bib.R")

```

```{r xaringan-themer, include = FALSE}
library(xaringanthemer)
style_solarized_light()
source("helper_functions/theme_lecture.R")
xaringanExtra::use_webcam()
xaringanExtra::use_tile_view()
```

## Introduction

+ About me: Dr Gabriel Geisler Mesevage (Gabriel is fine)
+ Financial/economic historian, mostly 19th c.